// <auto-generated />
using System;
using ListingsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ListingsApi.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

        modelBuilder.Entity("ListingsApi.Data.Entities.District", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("Name")
                .IsUnique();

            b.ToTable("Districts");

            b.HasData(
                new { Id = 1, Name = "Чиланзар" },
                new { Id = 2, Name = "Юнусабад" },
                new { Id = 3, Name = "Мирзо-Улугбек" });
        });

        modelBuilder.Entity("ListingsApi.Data.Entities.Listing", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("Address")
                .HasMaxLength(300)
                .HasColumnType("TEXT");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("TEXT");

            b.Property<int>("DistrictId")
                .HasColumnType("INTEGER");

            b.Property<double>("Price")
                .HasColumnType("REAL");

            b.Property<int>("Rooms")
                .HasColumnType("INTEGER");

            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("DistrictId");

            b.ToTable("Listings");

            b.HasData(
                new { Id = 1, Address = "Чиланзар, 12 кв., д. 4", CreatedAt = new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Utc), DistrictId = 1, Price = 48000.0, Rooms = 2, Title = "2-комн. рядом с метро Чиланзар" },
                new { Id = 2, CreatedAt = new DateTime(2026, 9, 5, 10, 30, 0, 0, DateTimeKind.Utc), DistrictId = 2, Price = 71000.0, Rooms = 3, Title = "3-комн. с ремонтом" },
                new { Id = 3, CreatedAt = new DateTime(2026, 9, 8, 14, 0, 0, 0, DateTimeKind.Utc), DistrictId = 3, Price = 32000.0, Rooms = 1, Title = "1-комн. студия" },
                new { Id = 4, Address = "Юнусабад, 4 кв.", CreatedAt = new DateTime(2026, 9, 12, 8, 15, 0, 0, DateTimeKind.Utc), DistrictId = 2, Price = 95000.0, Rooms = 4, Title = "4-комн. с видом на парк" },
                new { Id = 5, CreatedAt = new DateTime(2026, 9, 15, 11, 0, 0, 0, DateTimeKind.Utc), DistrictId = 1, Price = 52000.0, Rooms = 2, Title = "2-комн. после ремонта, тихий двор" },
                new { Id = 6, CreatedAt = new DateTime(2026, 9, 18, 16, 45, 0, 0, DateTimeKind.Utc), DistrictId = 2, Price = 36000.0, Rooms = 1, Title = "1-комн. у ТРЦ" },
                new { Id = 7, CreatedAt = new DateTime(2026, 9, 20, 9, 30, 0, 0, DateTimeKind.Utc), DistrictId = 3, Price = 66000.0, Rooms = 3, Title = "3-комн. семейная" },
                new { Id = 8, CreatedAt = new DateTime(2026, 9, 24, 12, 0, 0, 0, DateTimeKind.Utc), DistrictId = 1, Price = 39000.0, Rooms = 2, Title = "2-комн. срочно, торг" });
        });

        modelBuilder.Entity("ListingsApi.Data.Entities.Listing", b =>
        {
            b.HasOne("ListingsApi.Data.Entities.District", "District")
                .WithMany("Listings")
                .HasForeignKey("DistrictId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("District");
        });

        modelBuilder.Entity("ListingsApi.Data.Entities.District", b =>
        {
            b.Navigation("Listings");
        });
#pragma warning restore 612, 618
    }
}
